[versions]
# base setting
agp = "8.12.0"
kotlin = "2.0.21"
ksp = "2.0.0-1.0.21"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.9.2"

# sdk
compileSdk = "36"
minSdk = "24"

# compose
activityCompose = "1.10.1"
navigationCompose = "2.8.1"
composeBom = "2024.04.01"
jetbrainsKotlinJvm = "1.9.0"

# Hilt
hilt = "2.51.1"
hiltNavigationCompose = "1.2.0"

# Room
roomVersion = "2.6.1"

# Coil
coilVersion = "2.7.0"

# serialization
kotlinSerializationJson = "1.7.3"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
jetbrainsKotlinJvmVersion = "2.0.21"

[libraries]
android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilVersion" }

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Room
room-runtime = {group="androidx.room", name = "room-runtime" , version.ref = "roomVersion"}
room-compiler = {group="androidx.room", name = "room-compiler" , version.ref = "roomVersion"}
room-ktx = {group="androidx.room", name = "room-ktx" , version.ref = "roomVersion"}
room-paging = {group="androidx.room", name = "room-paging" , version.ref = "roomVersion"}

# Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }


[plugins]
# app 모듈에서 사용하는 기본 plugin setting
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# all - lib 모듈, app 모듈 상관 없이 사용가능한 gradle setting
all-hilt = { id = "all.hilt", version = "unspecified" }

# app - app 모듈에서 사용하는 gradle setting
application = { id = "app.application", version = "unspecified" }
app-flavor = { id = "app.flavor", version = "unspecified" }
app-compose = { id = "app.compose", version = "unspecified" }

# lib - lib 모듈에서 사용하는 gradle setting
library = { id = "lib.library", version = "unspecified" }
lib-flavor = { id = "lib.flavor", version = "unspecified" }
lib-compose = { id = "lib.compose", version = "unspecified" }
lib-network = { id = "lib.network", version = "unspecified" }
lib-room = { id = "lib.room", version = "unspecified" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvmVersion" }

