[versions]

# App Version
appVersionCode = "10000"
appVersionName = "01.00.00"

# base setting
agp = "8.9.1"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"

# KMP/CMP
composeMultiplatform = "1.8.0"

# sdk
compileSdk = "36"
minSdk = "26"

# AndroidX
coreKtx = "1.15.0"
coreSplashscreen = "1.0.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"

# Koin (DI - KMP compatible)
koin = "4.0.4"
koinCompose = "4.0.4"

# Ktor (Network - KMP)
ktor = "3.1.0"

# serialization
kotlinSerializationJson = "1.8.0"

# Coroutines
coroutines = "1.10.1"

# DateTime (KMP)
kotlinxDatetime = "0.6.1"

# Test
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

# DataStore
datastoreVersion = "1.1.1"

# AndroidX Material (Android only)
androidMaterial = "1.11.0"

# Supabase
supabase = "3.2.4"

# BuildKonfig (KMP BuildConfig)
buildkonfig = "0.17.1"
jetbrainsKotlinJvm = "2.2.0"

# kmp Navigation
navigation = "2.9.1"

# kmp lifecycle
navLifecycle = "2.9.1"

# In App Browser - by yjyoon-dev
kinappbrowser = "1.0.0"

# Kakao SDK
kakaoSdk = "2.20.6"

# Firebase SDK
googleServices = "4.4.2"
firebaseCrashlyticsPlugin = "3.0.3"
firebaseCrashlytics = "19.4.0"
firebaseAnalytics = "22.2.0"

[libraries]
# Gradle Plugins
android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
compose-multiplatform-gradle-plugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "composeMultiplatform" }

# AndroidX (Android only)
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }

# Koin (DI - KMP)
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koinCompose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koinCompose" }

# Ktor (Network - KMP)
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }

# DateTime (KMP)
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Lifecycle (KMP)
lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "navLifecycle" }
lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "navLifecycle" }

# Navigation (KMP)
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# DataStore
androidx-datastore-core = { group = "androidx.datastore", name = "datastore", version.ref = "datastoreVersion" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreVersion" }

# Supabase
supabase-auth = { group = "io.github.jan-tennert.supabase", name = "auth-kt", version.ref = "supabase" }
supabase-postgrest = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt", version.ref = "supabase" }
supabase-functions = { group = "io.github.jan-tennert.supabase", name = "functions-kt", version.ref = "supabase" }
supabase-compose-auth = { group = "io.github.jan-tennert.supabase", name = "compose-auth", version.ref = "supabase" }
supabase-compose-auth-ui = { group = "io.github.jan-tennert.supabase", name = "compose-auth-ui", version.ref = "supabase" }

# Build Konfig
buildkonfig-compiler = { module = "com.codingfeline.buildkonfig:buildkonfig-compiler", version.ref = "buildkonfig" }
buildkonfigGradlePlugin = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfig" }

# In App Browser - by yjyoon-dev
kinappbrowser = { module = "dev.yjyoon:kinappbrowser", version.ref = "kinappbrowser" }

# Kakao SDK
kakao-share = { group = "com.kakao.sdk", name = "v2-share", version.ref = "kakaoSdk" }
kakao-common = { group = "com.kakao.sdk", name = "v2-common", version.ref = "kakaoSdk" }

# Google SDK
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebaseAnalytics" }

[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

# Compose
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

# KSP
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# BuildKonfig
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }

# Convention Plugins (custom)
convention-android-library = { id = "android.library", version = "unspecified" }
convention-kmp-compose = { id = "kmp.compose", version = "unspecified" }
convention-android-app = { id = "android.app", version = "unspecified" }
convention-kmp-koin = { id = "kmp.koin", version = "unspecified" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

# Google SDK
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics-plugin = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }

[bundles]

supabase = [
    "supabase-auth",
    "supabase-postgrest",
    "supabase-functions",
    "supabase-compose-auth",
]

buildKonfig = [
    "buildkonfig-compiler",
    "buildkonfigGradlePlugin",
]

kakaoShare = [
    "kakao-share",
    "kakao-common",
]
